// Generated by Wrangler by running `wrangler types ./src/server/worker-configuration.d.ts`
interface Env {
  SESSION_SECRET: string;
  ASSETS_DIR: Fetcher;
  ASSETS: R2Bucket;
  Chat: DurableObjectNamespace;
  Auth: DurableObjectNamespace;
  Servers: DurableObjectNamespace;
}
